---
- name: Configure the NFS provisioner and OpenShift NFS PVC
  when: not remove_nfs_server|bool
  block:
    - name: Deploy the NFS Server
      include_tasks: configure-nfs-server.yml
      when: provision_nfs_server|bool and not delete_deployment|bool

    - name: Deploy the NFS provisioner
      include_tasks: nfs-provisioner.yml
      when: provision_nfs_client_provisoner|bool
    
    - name: Provision the PVC for the OpenShift internal registry
      include_tasks: configure_registry.yml
      when: configure_registry|bool

- name: remove nfs server
  include_tasks: remove-nfs-server.yml
  when: remove_nfs_server|bool
