- name: Copying over nfs-provisioner rbac
  copy:
    src: templates/nfs-provisioner-rbac.yaml
    dest: /usr/local/src/nfs-provisioner-rbac.yaml
    owner: root
    group: root
    mode: 0666

- name: Copying over nfs-provisioner deployment
  template:
    src: templates/nfs-provisioner-deployment.yaml.j2
    dest: /usr/local/src/nfs-provisioner-deployment.yaml
    owner: root
    group: root
    mode: 0666

- name: Copying over nfs-provisioner storageclass
  copy:
    src: templates/nfs-provisioner-sc.yaml
    dest: /usr/local/src/nfs-provisioner-sc.yaml
    owner: root
    group: root
    mode: 0666

- name: Copying over a sample PVC file for NFS
  template:
    src: templates/registry-pvc.yaml.j2
    dest: /usr/local/src/registry-pvc.yaml
    owner: root
    group: root
    mode: 0666
